force-app/apex-rest/objects/ApiEndpoint__mdt/ApiEndpoint__mdt.object-meta.xml
<CustomObject>
    <description>Contains base information about an endpoint</description>
    <label>Api Endpoint</label>
    <pluralLabel>Api Endpoints</pluralLabel>
</CustomObject>

force-app/apex-rest/objects/ApiEndpoint__mdt/fields/ApiName__c.field-meta.xml
<CustomField>
    <fullName>ApiName__c</fullName>
    <description>Api Name: /services/apexrest/&lt;apiname&gt;/&lt;version/&lt;endpoint&gt;
e.g. /services/apexrest/pricing/v1/products/1234</description>
    <inlineHelpText>Api Name: /services/apexrest/&lt;apiname&gt;/&lt;version/&lt;endpoint&gt;
e.g. /services/apexrest/pricing/v1/products/1234</inlineHelpText>
    <label>Api Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>placeholder</fullName>
                <default>true</default>
                <label>placeholder</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/apex-rest/objects/ApiEndpoint__mdt/fields/EndpointRegex__c.field-meta.xml
<CustomField>
    <fullName>EndpointRegex__c</fullName>
    <description>The regular expression to be used to capture the endpoint, excluding version and name
e.g. for services/apexrest/placeholder/v1/products/1234, the endpoint regex would be products/[0-9]*</description>
    <inlineHelpText>The regular expression to be used to capture the endpoint, excluding version and name
e.g. for services/apexrest/placeholder/v1/products/1234, the endpoint regex would be products/[0-9]*</inlineHelpText>
    <label>Endpoint Regex</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/apex-rest/objects/ApiEndpointVersion__mdt/ApiEndpointVersion__mdt.object-meta.xml
<CustomObject>
    <description>Contains versioning info for an Api Endpoint</description>
    <label>Api Endpoint Version</label>
    <pluralLabel>Api Endpoint Versions</pluralLabel>
</CustomObject>

force-app/main/default/objects/ApiEndpointVersion__mdt/fields/ApiEndpoint__c.field-meta.xml
<CustomField>
    <fullName>ApiEndpoint__c</fullName>
    <description>The associated base Api endpoint</description>
    <inlineHelpText>The associated base Api endpoint</inlineHelpText>
    <label>Api Endpoint</label>
    <referenceTo>ApiEndpoint__mdt</referenceTo>
    <relationshipLabel>Api Endpoint Versions</relationshipLabel>
    <relationshipName>ApiEndpointVersions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ApiEndpointVersion__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>The name of the IApiRequestHandler class that should be used when this endpoint is hit</description>
    <inlineHelpText>The name of the IApiRequestHandler class that should be used when this endpoint is hit</inlineHelpText>
    <label>Class Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApiEndpointVersion__mdt/fields/EndpointVersion__c.field-meta.xml
<CustomField>
    <fullName>EndpointVersion__c</fullName>
    <description>The version of the endpoint (v1, v2, etc.)</description>
    <inlineHelpText>The version of the endpoint (v1, v2, etc.)</inlineHelpText>
    <label>Endpoint Version</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>v1</fullName>
                <default>true</default>
                <label>v1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/apex-rest/objects/ApiEndpointVersion__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not the endpoint version is active</description>
    <inlineHelpText>Whether or not the endpoint version is active</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ApiUrlResolver.cls
/**
 * @author Thomas Wilkins
 * @description Class for resolving a URL based on endpoint configurations
 */ 
public with sharing class ApiUrlResolver {
    // custom metadata should be "mocked" for tests by directly setting this variable
    @TestVisible
    private List<ApiEndpointVersion__mdt> endpoints {
        get {
            if (this.endpoints == null) {
                // query the related list, because at the time of writing,
                // there is a bug where cross-object filters on custom metadata picklists does not work
                // see https://salesforce.stackexchange.com/questions/221868/unable-to-query-with-cross-object-pick-list-field-filter-on-custom-metadata-soql
                List<ApiEndpoint__mdt> apiEndpoints = [
                    SELECT Id,
                    (
                        SELECT 
                            EndpointVersion__c, ClassName__c,
                            ApiEndpoint__r.ApiName__c, 
                            ApiEndpoint__r.EndpointRegex__c 
                        FROM ApiEndpointVersions__r
                        WHERE EndpointVersion__c = :this.endpointVersion
                        AND IsActive__c = true
                    )
                    FROM ApiEndpoint__mdt
                    WHERE ApiName__c = :this.apiName
                ];
                this.endpoints = new List<ApiEndpointVersion__mdt>();
                // this should handle if you have multiple configs for different web services 
                for (ApiEndpoint__mdt apiEndpoint : apiEndpoints) {
                    this.endpoints.addAll(apiEndpoint.ApiEndpointVersions__r);
                }
            }
            return this.endpoints;
        } set;
    }

    @TestVisible
    private String apiName, endpointVersion;

    /**
     * Constructor
     * @param  apiName         The name of the api e.g. /services/apexrest/<apiName>/<endpointVersion>/<endpoint>
     * @param  endpointVersion The version of the endpoint e.g. /services/apexrest/<apiName>/<endpointVersion>/<endpoint>
     * @return                 this
     */ 
    public ApiUrlResolver(String apiName, String endpointVersion) {
        this.apiName = apiName;
        this.endpointVersion = endpointVersion;
    }

    /**
     * Attempts to match the current rest URL against configured endpoints
     * @param  url             a rest url to test for matches
     * @return                 The handler configured for the requested endpoint
     * @throws                 ApiExceptions.NotFoundException
     */ 
    public IApiRequestHandler resolve(String url) {
        for (ApiEndpointVersion__mdt endpoint : this.endpoints) {
            String fullRegex = '/' + 
                endpoint.ApiEndpoint__r.ApiName__c + '/' + 
                endpoint.EndpointVersion__c + '/' + 
                endpoint.ApiEndpoint__r.EndpointRegex__c;
            if (Pattern.matches(fullRegex, url)) {
                return (IApiRequestHandler)Type.forName(endpoint.ClassName__c).newInstance();
            } 
        }
        throw new ApiExceptions.NotFoundException('Endpoint: ' + url + ' not found.');
    }
}